apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: oteld
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
      otlp:
        endpoint: tempo-otel:4317
        tls: 
          insecure: true
        
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging,otlp]